#! /bin/sh

sxhkd &
~/.config/polybar/launch.sh &
picom &
nitrogen --restore &




# Workspaces
bspc monitor -d 1 2 3 4 5

# Window config
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config focused_border_color "#83a598"
bspc config normal_border_color "#454849"
